version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: .mvn/Dockerfile
    ports: ['8080:8080']
    networks: [application.net]
  healthcheck:
    image: busybox
    depends_on:
      app:
        condition: service_healthy
    command: echo "ready."
    networks: [application.net]
networks:
  application.net:
    driver: bridge
