version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    ports:
    - '5005:5005'
    - '8080:8080'
    networks: [application.net]
networks:
  application.net:
    driver: bridge
